general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 240                                 # 2 min
    on-timeout = loginctl lock-session            # lock screen
}

listener {
    timeout = 270                                 # 2.5 min (30s after lock)
    on-timeout = hyprctl dispatch dpms off        # turn display off
    on-resume = hyprctl dispatch dpms on          # turn back on when input
}
